### ISSUE TITLE
CUDA Memory Errors

### ISSUE THREAD

**Issue by AndrewToomey** [bryanchrist/MathNeuro#3]
Out of curiosity, what were the specs of the system that you ran your tests on?

I am trying to work with the MathNeuro.py, using the suggested parameters (for an 8b LLaMA 3.1 model) with 144Gb vRAM (3x A40) but I keep running into CUDA errors. I just want to make sure that I am not doing something wrong before I try a more powerful system.

I have been unsuccessful for a few hours now. No matter what I try, it always throws an error at the 'Running loglikelihood requests' line.

100%|██████████| 165/165 [00:00<00:00, 519.83it/s]
2024-10-30:14:04:49,179 INFO     [task.py:423] Building contexts for mmlu_formal_logic on rank 0...
100%|██████████| 126/126 [00:00<00:00, 545.16it/s]
2024-10-30:14:04:49,422 INFO     [task.py:423] Building contexts for race on rank 0...
100%|██████████| 1045/1045 [00:00<00:00, 3655.71it/s]
2024-10-30:14:04:49,740 INFO     [evaluator.py:457] Running loglikelihood requests
Running loglikelihood requests:   0%|          | 0/60348 [00:00<?, ?it/s]

Passed argument batch_size = auto:4.0. Detecting largest batch size

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File /workspace/MathNeuro/MathNeuro.py:185
    182 with open(results_path, "w") as outfile: 
    183     json.dump(results['results'], outfile)
--> 185 results = lm_eval.simple_evaluate( # call simple_evaluate
    186     model = 'hf',
    187     model_args = {'pretrained':model, 'dtype': 'bfloat16', 'tokenizer': tokenizer},
    188     tasks=args.eval_datasets,
    189     task_manager=task_manager,
    190     log_samples = False, 
    191     batch_size = 'auto:4'
    192 )
    193 results_path = f"{args.save_path}/eval_results/{args.model}/pre_results.json"
    194 os.makedirs(os.path.dirname(results_path), exist_ok=True)

File /workspace/MathNeuro/lm_eval/utils.py:397, in positional_deprecated.<locals>._wrapper(*args, **kwargs)
    391 if len(args) != 1 if inspect.ismethod(fn) else 0:
    392     print(
    393         f"WARNING: using {fn.__name__} with positional arguments is "
    394         "deprecated and will be disallowed in a future version of "
    395         "lm-evaluation-harness!"
    396     )
--> 397 return fn(*args, **kwargs)

File /workspace/MathNeuro/lm_eval/evaluator.py:296, in simple_evaluate(model, model_args, tasks, num_fewshot, batch_size, max_batch_size, device, use_cache, cache_requests, rewrite_requests_cache, delete_requests_cache, limit, bootstrap_iters, check_integrity, write_out, log_samples, evaluation_tracker, system_instruction, apply_chat_template, fewshot_as_multiturn, gen_kwargs, task_manager, verbosity, predict_only, random_seed, numpy_random_seed, torch_random_seed, fewshot_random_seed)
    287 if evaluation_tracker is not None:
    288     evaluation_tracker.general_config_tracker.log_experiment_args(
    289         model_source=model,
    290         model_args=model_args,
   (...)
    293         fewshot_as_multiturn=fewshot_as_multiturn,
    294     )
--> 296 results = evaluate(
    297     lm=lm,
    298     task_dict=task_dict,
    299     limit=limit,
    300     cache_requests=cache_requests,
    301     rewrite_requests_cache=rewrite_requests_cache,
    302     bootstrap_iters=bootstrap_iters,
    303     write_out=write_out,
    304     log_samples=True if predict_only else log_samples,
    305     system_instruction=system_instruction,
    306     apply_chat_template=apply_chat_template,
    307     fewshot_as_multiturn=fewshot_as_multiturn,
    308     verbosity=verbosity,
    309 )
    311 if lm.rank == 0:
    312     if isinstance(model, str):

File /workspace/MathNeuro/lm_eval/utils.py:397, in positional_deprecated.<locals>._wrapper(*args, **kwargs)
    391 if len(args) != 1 if inspect.ismethod(fn) else 0:
    392     print(
    393         f"WARNING: using {fn.__name__} with positional arguments is "
    394         "deprecated and will be disallowed in a future version of "
    395         "lm-evaluation-harness!"
    396     )
--> 397 return fn(*args, **kwargs)

File /workspace/MathNeuro/lm_eval/evaluator.py:468, in evaluate(lm, task_dict, limit, cache_requests, rewrite_requests_cache, bootstrap_iters, write_out, log_samples, system_instruction, apply_chat_template, fewshot_as_multiturn, verbosity)
    465         cloned_reqs.extend([req] * req.repeats)
    467 # run requests through model
--> 468 resps = getattr(lm, reqtype)(cloned_reqs)
    470 # put responses from model into a list of length K for each request.
    471 for x, req in zip(resps, cloned_reqs):

File /workspace/MathNeuro/lm_eval/api/model.py:371, in TemplateLM.loglikelihood(self, requests, disable_tqdm)
    367         context_enc, continuation_enc = self._encode_pair(context, continuation)
    369     new_reqs.append(((context, continuation), context_enc, continuation_enc))
--> 371 return self._loglikelihood_tokens(new_reqs, disable_tqdm=disable_tqdm)

File /workspace/MathNeuro/lm_eval/models/huggingface.py:990, in HFLM._loglikelihood_tokens(self, requests, disable_tqdm, override_bs)
    984 chunks = re_ord.get_batched(n=batch_size, batch_fn=batch_fn)
    985 pbar = tqdm(
    986     total=len(requests),
    987     disable=(disable_tqdm or (self.rank != 0)),
    988     desc="Running loglikelihood requests",
    989 )
--> 990 for chunk in chunks:
    991     inps = []
    992     cont_toks_list = []

File /workspace/MathNeuro/lm_eval/models/utils.py:433, in Collator.get_batched(self, n, batch_fn)
    429     values = self._reorder(
    430         [value[0] for value in self._arr_with_indices.values()]
    431     )
    432     batch = self.get_chunks(values, n=n, fn=batch_fn)
--> 433     yield from batch
    434 else:
    435     values = self._reorder(self._arr_with_indices)  # type: ignore

File /workspace/MathNeuro/lm_eval/models/utils.py:616, in Collator.get_chunks(_iter, n, fn)
    614 for i, x in enumerate(_iter):
    615     arr.append(x)
--> 616     if len(arr) == (fn(i, _iter) if fn else n):
    617         yield arr
    618         arr = []

File /workspace/MathNeuro/lm_eval/models/huggingface.py:923, in HFLM._batch_scheduler(self, pos, n_reordered_requests)
    919     return self.batch_sizes[sched]
    920 print(
    921     f"Passed argument batch_size = auto:{self.batch_schedule}. Detecting largest batch size"
    922 )
--> 923 self.batch_sizes[sched] = self._detect_batch_size(n_reordered_requests, pos)
    924 print(f"Determined largest batch size: {self.batch_sizes[sched]}")
    925 return self.batch_sizes[sched]

File /workspace/MathNeuro/lm_eval/models/huggingface.py:697, in HFLM._detect_batch_size(self, requests, pos)
    694     return batch_size
    696 try:
--> 697     batch_size = forward_batch()
    698 except RuntimeError as e:
    699     if "No executable batch size found" in str(e):

File /usr/local/lib/python3.10/dist-packages/accelerate/utils/memory.py:157, in find_executable_batch_size.<locals>.decorator(*args, **kwargs)
    155     raise RuntimeError("No executable batch size found, reached zero.")
    156 try:
--> 157     return function(batch_size, *args, **kwargs)
    158 except Exception as e:
    159     if should_reduce_batch_size(e):

File /workspace/MathNeuro/lm_eval/models/huggingface.py:692, in HFLM._detect_batch_size.<locals>.forward_batch(batch_size)
    688     test_batch = torch.ones(
    689         (batch_size, max_length), device=self.device
    690     ).long()
    691 for _ in range(5):
--> 692     out = F.log_softmax(self._model_call(test_batch, **call_kwargs), dim=-1)  # noqa: F841
    694 return batch_size

File /workspace/MathNeuro/lm_eval/models/huggingface.py:801, in HFLM._model_call(self, inps, attn_mask, labels)
    799 else:
    800     assert self.AUTO_MODEL_CLASS == transformers.AutoModelForCausalLM
--> 801     return self.model(inps).logits

File /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local/lib/python3.10/dist-packages/accelerate/hooks.py:170, in add_hook_to_module.<locals>.new_forward(module, *args, **kwargs)
    168         output = module._old_forward(*args, **kwargs)
    169 else:
--> 170     output = module._old_forward(*args, **kwargs)
    171 return module._hf_hook.post_forward(module, output)

File /usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py:1214, in LlamaForCausalLM.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict, cache_position, num_logits_to_keep)
   1209         logger.warning_once(
   1210             "Starting from v4.46, the `logits` model output will have the same type as the model (except at train time, where it will always be FP32)"
   1211         )
   1212     # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
   1213     # TODO: remove the float() operation in v4.46
-> 1214     logits = self.lm_head(hidden_states[:, -num_logits_to_keep:, :]).float()
   1216 loss = None
   1217 if labels is not None:
   1218     # Upcast to float if we need to compute the loss to avoid potential precision issues

File /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local/lib/python3.10/dist-packages/accelerate/hooks.py:170, in add_hook_to_module.<locals>.new_forward(module, *args, **kwargs)
    168         output = module._old_forward(*args, **kwargs)
    169 else:
--> 170     output = module._old_forward(*args, **kwargs)
    171 return module._hf_hook.post_forward(module, output)

File /usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py:114, in Linear.forward(self, input)
    113 def forward(self, input: Tensor) -> Tensor:
--> 114     return F.linear(input, self.weight, self.bias)

RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by bryanchrist** [comment]
Hello- thanks for reaching out! You can try a smaller batch size by replacing batch_size = 'auto:4'. Sometimes lm_eval will exceed the max memory of the system when trying to auto detect a batch size, which can throw a Cuda OOM error. 

We used 3 X A100 80GB GPUs for the Llama 3.1 8B experiments to be safe, but it didn't end up requiring the full memory. You can also try offloading the math and non-math parameter dictionaries to cpu if needed.

**Comment by AndrewToomey** [comment]
Thank you for your reply.

I can confirm that setting the batch_size to a smaller value ("3" instead of "auto:4") resolved the issue and the next run completed without any problems.
